version: "3.7"
services:
#  nginx:
#    image: nginx:1.25
#    container_name: nginx
#    restart: always
#    ports:
#      - "80:80"
#      - "443:443"
#    volumes:
#      - ./nginx.conf:/etc/nginx/nginx.conf
#    environment:
#      - TZ=Asia/Seoul
  redis:
    image: redis:6.2
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    labels:
      - name=redis
      - mode=standalone
    command: redis-server --port 6379

