spring:
  sql:
    init:
      mode: always
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/hello_cache
    username: user
    password: password
  cache:
    type: redis
  data:
    redis:
      host: localhost
      port: 6379
